# Site settings
title: Ryan Holmes
email: ryanclintonholmes@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: stunnedbeast
github_username:  themarblery
exclude: [
	".git",
	".gitignore",
	".DS_Store",
	"CNAME",
	"svg",
	"scss",
	".scss",
	".sass-cache",
	"package.json",
	"Gruntfile.js",
	"node_modules",
	"README.md",
	"bower.json"
]

# Build settings
markdown: kramdown
